name: Java CI

on:
  push:
    branches:
      - 1.8.9
      - Legacy1.12.2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Deploy javadoc 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.PAGE_DEPLOY_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build/docs/javadoc # The folder the action should deploy.
      - name : Publish to maven
        env:
          MAVEN_PUBLISH_TOKEN: ${{ secrets.MAVEN_PUBLISH_TOKEN }} 
        run: ./gradlew publish    
